robot_arm:
    # Publish all joint states -----------------------------------
    joints_update:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    
    # Position Controllers ---------------------------------------
    joint1_controller:
      type: position_controllers/JointPositionController
      joint: base_joint_1
      pid: {p: 1.0, i: 1.0, d: 0.0}
    joint2_controller:
      type: position_controllers/JointPositionController
      joint: shoulder_joint_2
      pid: {p: 1.0, i: 1.0, d: 0.0}
    joint3_controller:
      type: position_controllers/JointPositionController
      joint: elbow_joint_3
      pid: {p: 1.0, i: 1.0, d: 0.0}
    joint4_controller:
      type: position_controllers/JointPositionController
      joint: wrist_joint_4
      pid: {p: 1.0, i: 1.0, d: 0.0}
    joint5_controller:
      type: position_controllers/JointPositionController
      joint: roll_wrist_joint_5
      pid: {p: 1.0, i: 1.0, d: 0.0}